version: '2'
services:
  redis:
    image: "redis:alpine"
    restart: always

  node:
    build: .
    restart: always
    ports:
     - "${FOOD_PORT}:3000"
    depends_on:
     - redis
    links:
     - redis
