version: '2'
services:
  redis:
    image: "redis:alpine"

  node:
    build: .
    volumes:
     - .:/usr/src/app
    ports:
     - "${FOOD_PORT}:3000"
    depends_on:
     - redis
    links:
     - redis