name: deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: echo test
        host: ${{ secrets.SSH_DEPLOY_TARGET }}
        user: ${{ secrets.SSH_DEPLOY_USER }}
        key: ${{ secrets.SSH_DEPLOY_KEY }}
        args: ${{ secrets.SSH_EXTRA_ARGS }}
