name: deployment

on:
  push:
    branches: 
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Upload the deploy key, connect, and trigger deployment
      run: |
        mkdir -p ~/.ssh
        echo $SSH_HOST_FINGERPRINT >> ~/.ssh/known_hosts
        eval $(ssh-agent -s)
        ssh-add <(echo "$SSH_DEPLOY_KEY")
        $SSH_DEPLOY_CMD
        
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        SSH_DEPLOY_CMD: ${{ secrets.SSH_DEPLOY_CMD }}
        SSH_HOST_FINGERPRINT: ${{ secrets.SSH_HOST_FINGERPRINT }}
        
        
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: benjamin-hackl.at
        username: www-data
        key: ${{ secrets.SSH_DEPLOY_KEY }}
        port: 9073
        script: "echo test"
